function LoadObjectList()
{
    var object_list = [   
    {
        "name": "Skull",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"10"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Mandible",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"5"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_03",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_04",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
        "select": "false", 
    },
    {
        "name": "Spine_Bone_05",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_06",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_07",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_08",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_09",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Spine_Bone_10",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Canine_Left",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Canine_Right",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Incisor_Left_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Incisor_Left_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Incisor_Right_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Incisor_Right_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Molar_Left_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Molar_Left_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Molar_Right_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Molar_Right_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Premolar_Left_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Premolar_Left_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Premolar_Right_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Lower_Premolar_Right_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Canine_Left",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Canine_Right",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Incisor_Left_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Incisor_Left_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Incisor_Right_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Incisor_Right_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Molar_Left_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Molar_Left_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Molar_Right_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Molar_Right_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Premolar_Left_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Premolar_Left_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Premolar_Right_01",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    },
    {
        "name": "Upper_Premolar_Right_02",
        "path": "2015/09/",
        "diffuse": "SkullTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
        "select": "false",
    }, 
    // BRAIN TEXTURES
    {
        "name": "Spinal_Cord_Lower",
        "path": "2015/09/",
        "diffuse": "brainTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
        "select": "false",
    },
    {
        "name": "Nerves_Left",
        "path": "2015/09/",
        "diffuse": "brainTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
        "select": "false",
    },
    {
        "name": "Nerves_Right",
        "path": "2015/09/",
        "diffuse": "brainTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
        "select": "false",
    },
    // EYEBALL TEXTURE
    {
        "name": "Eye_Ball_Inner_Left",
        "path": "2015/09/",
        "diffuse": "EyeBallTexture.jpg",
       "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Eye_Ball_Inner_Right",
        "path": "2015/09/",
        "diffuse": "EyeBallTexture.jpg",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},  
    },
    // MUSCLE BODY TEXTURE
    {
        "name": "Frontalis_Muscle",
        "path": "2015/09/",
        "diffuse": "muscles_bodyTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Temporal_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles_bodyTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Temporal_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles_bodyTexture.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    // MUSCLES TEXTURE
    {
        "name": "Orbicularis_Oris_Muscle",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Orbicularis_Oculi_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0.8", "y":"1.3", "z":"2.8"}, 
        "target": { "x":"0.1", "y":"1.7", "z":"0"}, 
    },
    {
        "name": "Orbicularis_Oculi_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Masseter_Superficial_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Masseter_Superficial_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Orbicularis_Oris_Muscle",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Nasal_Cartilage",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Sternocleidomastoid_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Sternocleidomastoid_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Splenius_Cervicis_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Splenius_Cervicis_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Procerus_Muscle_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Procerus_Muscle_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Depressor_Supercilii_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Depressor_Supercilii_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Corrugator_Supercilii_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Corrugator_Supercilii_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Depressor_Speti_Nasi_Muscle",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Levator_Labii_Superioris_Muscle_Left_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Levator_Labii_Superioris_Muscle_Left_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Levator_Labii_Superioris_Muscle_Right_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Levator_Labii_Superioris_Muscle_Right_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Levator_Anguli_Oris_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Levator_Anguli_Oris_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Nasalis_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Nasalis_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"}, 
    },
    {
        "name": "Zygomaticus_Major_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Zygomaticus_Major_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Zygomaticus_Minor_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Zygomaticus_Minor_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Mentalis_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Mentalis_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Depressor_Labii_Inferioris_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Depressor_Labii_Inferioris_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Depressor_Anguli_Oris_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Depressor_Anguli_Oris_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Masseter_Deep_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Masseter_Deep_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Buccinator_Muscle_Left",
       "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Buccinator_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Risorius_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Risorius_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Superior_Auricular_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Superior_Auricular_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Posterior_Auricular_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Posterior_Auricular_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Sternohyoid_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Sternohyoid_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Sternothyroideus_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Sternothyroideus_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Stylohyoid_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Stylohyoid_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Thyrohyoid_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Thyrohyoid_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Mylohyoid_Muscle",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Digastric_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Digastric_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Hyoglossus_Muscle_Left",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Hyoglossus_Muscle_Right",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Left_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Left_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Left_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Left_04",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Right_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Right_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Right_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Levator_Scapulae_Muscle_Right_04",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalene_Muscle_Left_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalene_Muscle_Left_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalene_Muscle_Left_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalene_Muscle_Right_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalene_Muscle_Right_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalene_Muscle_Right_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Anterior_Muscle_Left_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Anterior_Muscle_Left_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Anterior_Muscle_Left_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Anterior_Muscle_Right_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Anterior_Muscle_Right_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Anterior_Muscle_Right_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Posterior_Muscle_Left_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Posterior_Muscle_Left_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Posterior_Muscle_Left_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Posterior_Muscle_Right_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Posterior_Muscle_Right_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Scalenus_Posterior_Muscle_Right_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Left_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Left_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Left_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Left_04",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Left_05",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Right_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Right_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Right_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Right_04",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Capitis_Muscle_Right_05",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Left_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Left_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Left_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Left_04",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Right_01",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Right_02",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Right_03",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    {
        "name": "Semispinalis_Cervicis_Muscle_Right_04",
        "path": "2015/09/",
        "diffuse": "muscles.png",
        "position": { "x":"0", "y":"0", "z":"0"}, 
        "target": { "x":"0", "y":"0", "z":"0"},
    },
    ];
    return object_list;
 }




